version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - monitoring
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    networks:
      - monitoring
    depends_on:
      - logstash

  logstash:
    image: logstash:8.13.4
    command: >
      bash -c "bin/logstash-plugin install logstash-output-loki &&
               bin/logstash -f /usr/share/logstash/pipeline/logstash.conf"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "514:514/udp"
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
