{
 "title": "NFSU_FW Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n\n<body>\n  <center>\n    <img src=\"https://upload.wikimedia.org/wikipedia/en/9/96/National_Forensic_Sciences_University_Logo.png\" alt=\"CoE-CS\" width=\"100\" height=\"118\">\n  </center>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "expr": "{type=\"syslog\"} ",
     "legendFormat": "{{devname}}"
    }
   ]
  },
  {
   "title": "Campus Overview (Log Count By Policies) - 1m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(policyname) (count_over_time({type=\"syslog\"} |logfmt | policyname=~\"Bypass URL|COEDF-ITC 6th Floor|Cisco Ctrl|Computer-Labs|Cyber-Staff|Hostels|NFSU-CAMPUS-WIFI|NFSU_Guest|Other-Staff|Server & Network Devices|blocked_Countries|others\" | __error__=`` [1m]))",
     "legendFormat": "{{d}}"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n\n<body>\n  <center>\n    <img src=\"https://raw.githubusercontent.com/CoE-CS/Images/main/CoECS%20logo.png\" width=\"200\" height=\"65\">\n  </center>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "expr": "{type=\"syslog\"} ",
     "legendFormat": "{{devname}}"
    }
   ]
  },
  {
   "title": "App Services - Auto",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by(app) (count_over_time({type=\"syslog\"} | logfmt | app=~\"Acrobat.Cloud|Adobe.Web|Amazon.AWS|Amazon.AWS_S3|Amazon.Ads|Amazon.CloudFront|Amazon.Mobile|Amazon.Services|Amazon.Video|Android|AnyDesk|Apple.Maps|Apple.Push.Notification|Apple.Services|Apple.Store|ArcGIS|Apple.iPhone|Arkoselabs.Captcha|Authd HTTP|Authd HTTPS|Avast.Service|Baidu.Services|BitTorrent|Bitdefender.Service|Bitly|Blogger|Brightcove|Chrome.Remote.Desktop|Clash.Of.Clans|Console Management(SSH)|Console Management(Telnet)|Crashlytics|DHCP/DHCP Relay|DHCP6|DNS|DNS.Over.HTTPS|DNS.Over.TLS|DNS_Dynamic.Update|DTLS|Dell.Service|Discord|Disqus|DotVPN|Dropbox|DuckDuckGo.Search|Duolingo|ESP.UDP|Epic.Games|Facebook|Facebook_Messenger.VoIP.Call|File.Upload.HTTP|Facebook_Video.Play|Firefox.Update|Github|Gmail|Godaddy|Google.Accounts|Google.Ads|Google.Analytics|Google.Calendar|Google.Chat_Video.Call|Google.Data.Saver|Google.Play|Google.Push.Notification|Google.Services|Google.Translate|Grindr|HTTP|HTTP.Audio|HTTP.BROWSER|HTTP.BROWSER_Chrome|HTTP.BROWSER_Edge|HTTP.BROWSER_Firefox|HTTP.BROWSER_IE|HTTP.Download.Accelerator|HTTP.Segmented.Download|HTTPS|HTTPS.BROWSER|Hoxx.VPN|Hubspot|IMAPS|IMDB|ISAKMP|Imo|Instagram|Intel.Services|Jabber|LDAP_UDP|League.Of.Legends|LinkedIn|MMS|MPTCP|MQTT|MS-SQL|MSSQL|Mailchimp|MYSQL|McAfee.Update|Mega|Mendeley|Microsoft.Authentication|Microsoft.Azure|Microsoft.Azure.Application.Insights|Microsoft.CDN|Microsoft.Intune|Microsoft.Office.365|Microsoft.Office.365.Portal|Microsoft.Office.Online|Microsoft.Office.Update|Microsoft.OneNote|Microsoft.Outlook|Microsoft.Outlook.Office.365|Microsoft.Portal|Microsoft.Product.Activation|Microsoft.SharePoint|Microsoft.Store|Microsoft.Teams|Microsoft.Windows.Update|Mobile.Legends|Monero.Cryptocurrency.Miner|Moodle|NTP|NetBIOS.Name.Service|Netflix|OCSP|OneDrive|OpenAI.ChatGPT|Opera.Turbo|PING|POP3S|PayPal|Ping|Pinterest|Proxy.HTTP|QUIC|QuickHeal.Update|Quora|RADIUS|Reddit|Riot.Games|Root.Certificate.URL|SAP.Concur|SIP|SMTP|SMTPS|SNMP_GetRequest|SQUID|SSL|SSL_TLSv1.0|SSL_TLSv1.1|SSL_TLSv1.2|SSL_TLSv1.3|STUN|Salesforce|Samsung.Cloud|Scribd|Shazam|Shopify|Skype|Skype.Portals|Slack|Slideshare|Snapchat|SolarWinds|Speedtest|Spotify|Steam|TCO-8080|TeamViewer|Telegram|Tencent.Services|Teredo|Thunder.VPN|TikTok|Tor|Trace.Route|Truecaller|Tumblr|Twilio|Twitter|Uber|UltraViewer|UserVoice|VLC|Viber|Vimeo|Wattpad|WeChat|Web Management|Web Management(HTTPS)|WebEx|WhatsApp|WhatsApp_File.Transfer|WhatsApp_VoIP.Call|WhatsApp_Web|Wikipedia|Windows.Push.Notification|Xbox|YY.Voice|Yahoo.Accounts|Yahoo.Finance|Yahoo.Mail|Yahoo.Search|Yahoo.Services|Yandex|YouTube|Zendesk|Zoom|iCloud|netbios forward\" | __error__!=\"LogfmtParserErr\" [$__auto])))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Recent Block Activity - 5m",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by(msg, srcip) (count_over_time({type=\"syslog\"} | logfmt | action =~ `block|blocked` | __error__=`` [5m])))",
     "legendFormat": "{{msg}}-{{srcip}}"
    }
   ]
  },
  {
   "title": "Ports - 1m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(service) (count_over_time({type=\"syslog\"} | logfmt | service=~\"NetBIOS|SMB|SSH|MYSQL|RDP|FTP|POP3|SMTP|DHCP|KERBEROS|RLOGIN|NESSUS|TELNET\"| __error__=`` [30s]))",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Service Risk - 1m",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(apprisk) (count_over_time({type=\"syslog\"} | logfmt | apprisk =~ `high` | __error__=`` [15s]))",
     "legendFormat": "{{apprisk}}"
    }
   ]
  },
  {
   "title": "Ongoing Ports - 1m",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by(dstport, logid) (count_over_time({type=\"syslog\"} | logfmt | type_extracted=\"utm\" |__error__=`` [1s])))",
     "legendFormat": "{{dstport}}"
    }
   ]
  },
  {
   "title": "Logs From Nations",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 9, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "sum by (dstcountry) (count_over_time({type=~\"syslog\"} | logfmt | dstcountry != \"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Identified OS - 1m",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(osname) (count_over_time({type=\"syslog\"} | logfmt | osname=~\"Android|Windows|iOS|iPadOS|macOS\"|  __error__!=\"LogfmtParserErr\"[1m]))",
     "legendFormat": "{{srcip}}"
    }
   ]
  },
  {
   "title": "Malicious Event - 3h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(attack, srcip, dstip, user) (count_over_time({type=\"syslog\"} | logfmt | subtype=\"ips\" [3h]))",
     "legendFormat": "{{attack}} _ {{dstip}} _ {{scrip}} _ {{user}}"
    }
   ]
  },
  {
   "title": "Denied Request - 1m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by(srcip) (count_over_time({type=\"syslog\"} | logfmt | action =~ `deny` | __error__=`` [1m])))",
     "legendFormat": "{{srcip}}"
    }
   ]
  },
  {
   "title": "Logs by Devices - 5m",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(devtype) (count_over_time({type=\"syslog\"} | logfmt | devtype =~ `Computer|Home & Office|Laptop|Mobile|Mobile Generic|Phone|Tablet|Printer|Proxy Server|Router|Server` [5m]))",
     "legendFormat": "{{devname}}"
    }
   ]
  },
  {
   "title": "SIEM Logs Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "count_over_time({type=\"syslog\"} |= ``[15m])",
     "rawSql": "SELECT arrayJoin(ruleActions) as ruleAction,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(hasAll(ruleTags, arrayPopBack([${tags}])), $tags)\nAND $__conditionalAll(has(ruleActions, '${ruleActions}'), $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\n\n\nGROUP BY time, ruleAction\nORDER BY time"
    }
   ]
  },
  {
   "title": "Packets - One Cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({type=\"syslog\"} | logfmt | __error__=`` [$__range]))",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(1, sum by(dstip, dstcountry) (count_over_time({type=~\"syslog\"} | logfmt | __error__=`` [1m])))",
     "legendFormat": "{{dstcountry}}-{{dstip}}"
    }
   ]
  },
  {
   "title": "Destination Sources ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(dstcountry) (count_over_time({type=\"syslog\"} | logfmt | type_extracted = `utm` [1m]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(devid) (count_over_time({type=~\"syslog\"} | logfmt | __error__!=\"LogfmtParserErr\" [$__interval]))  "
    }
   ]
  }
 ]
}